services:
  traefik:
    image: traefik:v3.6.8
    container_name: traefik
    command:
      - "--configfile=/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/routes.yml:/traefik/routes.yml:ro
      - ./traefik/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./website:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`cysgroup10.local`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.middlewares=rate-limit@file,secure-headers@file"
    networks:
      - web

  nginx2:
    image: nginx:alpine
    container_name: nginx2
    volumes:
      - ./website2:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx2.rule=Host(`site2.cysgroup10.local`)"
      - "traefik.http.routers.nginx2.entrypoints=websecure"
      - "traefik.http.routers.nginx2.tls=true"
      - "traefik.http.routers.nginx2.middlewares=rate-limit@file,secure-headers@file"
    networks:
      - web

networks:
  web:
    driver: bridge
